language: android
dist: trusty
android:
  components:
    - build-tools-29.0.0
    - android-29
    - extra
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-29
    #- sys-img-armeabi-v7a-android-17